<template>
  <div class="demo-space-x">
    <VBadge
      dot
      color="success"
      offset-x="-1"
      offset-y="-1"
    >
      <VIcon
        size="25"
        icon="mdi-instagram"
      />
    </VBadge>

    <VBadge
      dot
      color="secondary"
      offset-x="-1"
      offset-y="-1"
    >
      <VIcon
        size="25"
        icon="mdi-instagram"
      />
    </VBadge>

    <VBadge
      dot
      color="success"
      offset-x="-1"
      offset-y="-1"
    >
      <VIcon
        size="25"
        icon="mdi-instagram"
      />
    </VBadge>

    <VBadge
      dot
      color="info"
      offset-x="-1"
      offset-y="-1"
    >
      <VIcon
        size="25"
        icon="mdi-instagram"
      />
    </VBadge>

    <VBadge
      dot
      color="warning"
      offset-x="-1"
      offset-y="-1"
    >
      <VIcon
        size="25"
        icon="mdi-instagram"
      />
    </VBadge>

    <VBadge
      dot
      color="error"
      offset-x="-1"
      offset-y="-1"
    >
      <VIcon
        size="25"
        icon="mdi-instagram"
      />
    </VBadge>
  </div>
</template>
